<?php
/**
 * ProgramsPlatformsLocalesApi
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\DownloadStatsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Download Stats API docs
 *
 * To access the API: 1. Register a client with the proper permissions (`download_stats_api.*`) in the [Softonic OAuth Admin](https://oauth-admin.softonic.com) 1. Retrieve a token for that client with the proper scopes from the [Softonic OAuth API](https://oauth-v2.softonic.com). 1. Copy the token in the input field at the top of the page
 *
 * OpenAPI spec version: 1.68.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Softonic\DownloadStatsApiSdk\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Softonic\DownloadStatsApiSdk\ApiException;
use Softonic\DownloadStatsApiSdk\Configuration;
use Softonic\DownloadStatsApiSdk\HeaderSelector;
use Softonic\DownloadStatsApiSdk\ObjectSerializer;

/**
 * ProgramsPlatformsLocalesApi Class Doc Comment
 *
 * @category Class
 * @package  Softonic\DownloadStatsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsPlatformsLocalesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getProgramPlatformLocale
     *
     * Get the list of the downloads stats for a given program platform locale
     *
     * @param  string $id_program Program identifier (required)
     * @param  string $id_platform Platform identifier (required)
     * @param  string $id_locale Locale identifier (required)
     * @param  float $days_ago Take into account downloads from last given days (optional)
     *
     * @throws \Softonic\DownloadStatsApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Softonic\DownloadStatsApiSdk\Client\Model\ProgramPlatformLocale
     */
    public function getProgramPlatformLocale($id_program, $id_platform, $id_locale, $days_ago = null)
    {
        list($response) = $this->getProgramPlatformLocaleWithHttpInfo($id_program, $id_platform, $id_locale, $days_ago);
        return $response;
    }

    /**
     * Operation getProgramPlatformLocaleWithHttpInfo
     *
     * Get the list of the downloads stats for a given program platform locale
     *
     * @param  string $id_program Program identifier (required)
     * @param  string $id_platform Platform identifier (required)
     * @param  string $id_locale Locale identifier (required)
     * @param  float $days_ago Take into account downloads from last given days (optional)
     *
     * @throws \Softonic\DownloadStatsApiSdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Softonic\DownloadStatsApiSdk\Client\Model\ProgramPlatformLocale, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProgramPlatformLocaleWithHttpInfo($id_program, $id_platform, $id_locale, $days_ago = null)
    {
        $returnType = '\Softonic\DownloadStatsApiSdk\Client\Model\ProgramPlatformLocale';
        $request = $this->getProgramPlatformLocaleRequest($id_program, $id_platform, $id_locale, $days_ago);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Softonic\DownloadStatsApiSdk\Client\Model\ProgramPlatformLocale',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProgramPlatformLocaleAsync
     *
     * Get the list of the downloads stats for a given program platform locale
     *
     * @param  string $id_program Program identifier (required)
     * @param  string $id_platform Platform identifier (required)
     * @param  string $id_locale Locale identifier (required)
     * @param  float $days_ago Take into account downloads from last given days (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProgramPlatformLocaleAsync($id_program, $id_platform, $id_locale, $days_ago = null)
    {
        return $this->getProgramPlatformLocaleAsyncWithHttpInfo($id_program, $id_platform, $id_locale, $days_ago)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProgramPlatformLocaleAsyncWithHttpInfo
     *
     * Get the list of the downloads stats for a given program platform locale
     *
     * @param  string $id_program Program identifier (required)
     * @param  string $id_platform Platform identifier (required)
     * @param  string $id_locale Locale identifier (required)
     * @param  float $days_ago Take into account downloads from last given days (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProgramPlatformLocaleAsyncWithHttpInfo($id_program, $id_platform, $id_locale, $days_ago = null)
    {
        $returnType = '\Softonic\DownloadStatsApiSdk\Client\Model\ProgramPlatformLocale';
        $request = $this->getProgramPlatformLocaleRequest($id_program, $id_platform, $id_locale, $days_ago);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProgramPlatformLocale'
     *
     * @param  string $id_program Program identifier (required)
     * @param  string $id_platform Platform identifier (required)
     * @param  string $id_locale Locale identifier (required)
     * @param  float $days_ago Take into account downloads from last given days (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getProgramPlatformLocaleRequest($id_program, $id_platform, $id_locale, $days_ago = null)
    {
        // verify the required parameter 'id_program' is set
        if ($id_program === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_program when calling getProgramPlatformLocale'
            );
        }
        // verify the required parameter 'id_platform' is set
        if ($id_platform === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_platform when calling getProgramPlatformLocale'
            );
        }
        // verify the required parameter 'id_locale' is set
        if ($id_locale === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_locale when calling getProgramPlatformLocale'
            );
        }

        $resourcePath = '/programs/{id_program}/platforms/{id_platform}/locales/{id_locale}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($days_ago !== null) {
            $queryParams['daysAgo'] = ObjectSerializer::toQueryValue($days_ago);
        }

        // path params
        if ($id_program !== null) {
            $resourcePath = str_replace(
                '{' . 'id_program' . '}',
                ObjectSerializer::toPathValue($id_program),
                $resourcePath
            );
        }
        // path params
        if ($id_platform !== null) {
            $resourcePath = str_replace(
                '{' . 'id_platform' . '}',
                ObjectSerializer::toPathValue($id_platform),
                $resourcePath
            );
        }
        // path params
        if ($id_locale !== null) {
            $resourcePath = str_replace(
                '{' . 'id_locale' . '}',
                ObjectSerializer::toPathValue($id_locale),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
