<?php
/**
 * TotalItemsPagePerPageTotalPagesNextModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\DownloadStatsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * download-stats-api
 *
 * To see the project documentation go to https://download-stats-api-v2.docs.softonic.io/
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Softonic\DownloadStatsApiSdk;

/**
 * TotalItemsPagePerPageTotalPagesNextModelTest Class Doc Comment
 *
 * @category    Class
 * @description TotalItemsPagePerPageTotalPagesNextModel
 * @package     Softonic\DownloadStatsApiSdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TotalItemsPagePerPageTotalPagesNextModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TotalItemsPagePerPageTotalPagesNextModel"
     */
    public function testTotalItemsPagePerPageTotalPagesNextModel()
    {
    }

    /**
     * Test attribute "total_items"
     */
    public function testPropertyTotalItems()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }

    /**
     * Test attribute "per_page"
     */
    public function testPropertyPerPage()
    {
    }

    /**
     * Test attribute "total_pages"
     */
    public function testPropertyTotalPages()
    {
    }

    /**
     * Test attribute "next"
     */
    public function testPropertyNext()
    {
    }
}
