<?php
/**
 * DownloadStatsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\DownloadStatsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Download Stats API docs
 *
 * To access the API: 1. Register a client with the proper permissions (`download-stats-api.*`) in the [Softonic OAuth Admin](https://oauth-admin.softonic.com) 1. Retrieve a token for that client with the proper scopes from the [Softonic OAuth API](https://oauth-v2.softonic.com). 1. Copy the token in the input field at the top of the page
 *
 * OpenAPI spec version: 1.53.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\DownloadStatsApiSdk;

use \Softonic\DownloadStatsApiSdk\Configuration;
use \Softonic\DownloadStatsApiSdk\ApiException;
use \Softonic\DownloadStatsApiSdk\ObjectSerializer;

/**
 * DownloadStatsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\DownloadStatsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DownloadStatsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getDownloadStat
     *
     * Retrieves the given downloads statistics.
     *
     */
    public function testGetDownloadStat()
    {
    }

    /**
     * Test case for getDownloadStats
     *
     * Get the list of the downloads statistics for a given app.
     *
     */
    public function testGetDownloadStats()
    {
    }

    /**
     * Test case for postDownloadStats
     *
     * Creates the downloads statistics for a given app.
     *
     */
    public function testPostDownloadStats()
    {
    }

    /**
     * Test case for putDownloadStats
     *
     * Replaces the given downloads statistics.
     *
     */
    public function testPutDownloadStats()
    {
    }
}
