<?php
/**
 * ProgramsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\DownloadStatsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * download-stats-api
 *
 * To see the project documentation go to https://download-stats-api-v2.docs.softonic.io/
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\DownloadStatsApiSdk;

use \Softonic\DownloadStatsApiSdk\Configuration;
use \Softonic\DownloadStatsApiSdk\ApiException;
use \Softonic\DownloadStatsApiSdk\ObjectSerializer;

/**
 * ProgramsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\DownloadStatsApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for findProgram
     *
     * Get the list of the downloads stats ordered by downloads.
     *
     */
    public function testFindProgram()
    {
    }

    /**
     * Test case for getProgramPlatform
     *
     * Get the list of the downloads stats for a given program platform.
     *
     */
    public function testGetProgramPlatform()
    {
    }

    /**
     * Test case for getProgramPlatformLanguage
     *
     * Get the list of the downloads stats for a given program platform language.
     *
     */
    public function testGetProgramPlatformLanguage()
    {
    }
}
